---
Transform: AWS::Serverless-2016-10-31
# Parameters:
Resources:
  sectorTable:
    Type : AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "gameId"
          AttributeType: "N"
        - AttributeName: "sectorId"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "gameId"
          KeyType: "HASH"
        - AttributeName: "sectorId"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
  gameTable:
    Type : AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "gameId"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "gameId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
  gameHttpEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          tableName: !Ref gameTable
      Handler: generate_map.handler
      Runtime: python3.7
      CodeUri: ./smr/api/game_api/game_endpoint.py
      Description: game endpoint
      MemorySize: 256
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref gameTable
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /game
            Method: ANY
  generateMapEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          tableName: !Ref sectorTable
      Handler: generate_map.handler
      Runtime: python3.7
      CodeUri: ./smr/api/game_api/generate_map.py
      Description: generate map API
      MemorySize: 256
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref sectorTable
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /map/generate
            Method: ANY
