---
Transform: AWS::Serverless-2016-10-31
# Parameters:
Resources:
  sectorTable: 
    Type : AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "gameId"
          AttributeType: "N"
        - AttributeName: "sectorId"
          AttributeType: "N" 
      KeySchema: 
        - AttributeName: "gameId"
          KeyType: "HASH"
        - AttributeName: "sectorId"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 1
  gameTable: 
    Type : AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "gameId"
          AttributeType: "N" 
      KeySchema: 
        - AttributeName: "gameId"
          KeyType: "HASH" 
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 1
  gameHttpEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.7
      InlineCode: |
        import boto3

        def handler(event, context):
          return "Allll good"
      Description: game endpoint
      MemorySize: 256
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref gameTable
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /game
            Method: ANY
  sectorEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.7
      InlineCode: | 
        def handler(event, context):
          return "placeholder"
      Description: game endpoint
      MemorySize: 256
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref sectorTable
      Events:
        Generic:
          Type: Api
          Properties:
            Path: /sector
            Method: POST
        UpdateSector:
          Type: Api
          Properties:
            Path: /sector/{gameId}/{sectorId}
            Method: POST
        AddPortToSector:
          Type: Api
          Properties:
            Path: /sector/{gameId}/{sectorId}/port
            Method: POST
        AddSectors:
          Type: Api
          Properties:
            Path: /sectors
            Method: POST
